#!/usr/bin/env bash
#===========================================================
# deploy-feed.sh - Deploy opkg feed to GitHub Pages
#
# Takes the feed generated by create-opkg-feed.sh and pushes
# it to the gh-pages branch of the repository, making it
# available at:
#   https://vincenzosco.github.io/Vortex-A9100-Linux-Image/opkg/
#
# Usage:
#   ./scripts/deploy-feed.sh              # Deploy current feed
#   ./scripts/deploy-feed.sh --version 1.0.1  # Tag with version
#   ./scripts/deploy-feed.sh --dry-run    # Show what would be pushed
#
# Prerequisites:
#   - git installed and configured
#   - Push access to the repository
#   - GitHub Pages enabled for the repo (Settings > Pages)
#===========================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FEED_DIR="${SCRIPT_DIR}/opkg-feed/feed"
VERSION="1.0.0"
DRY_RUN=false

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }
step()  { echo -e "${BLUE}[STEP]${NC}  $*"; }

# Parse args
while [[ $# -gt 0 ]]; do
    case "$1" in
        --version) VERSION="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        -h|--help)
            cat << EOF
Usage: $0 [OPTIONS]

Deploy the opkg feed to GitHub Pages (gh-pages branch).

Options:
  --version X.Y.Z  Version tag for the deployment
  --dry-run        Show what would be pushed without actually pushing
  -h, --help       Show this help

The feed will be available at:
  https://vincenzosco.github.io/Vortex-A9100-Linux-Image/opkg/
EOF
            exit 0 ;;
        *) error "Unknown option: $1"; exit 1 ;;
    esac
done

# === Check prerequisites ===
check_prereqs() {
    step "Checking prerequisites..."
    
    if [ ! -d "${FEED_DIR}" ] || [ ! -f "${FEED_DIR}/Packages.gz" ]; then
        error "Feed not found at ${FEED_DIR}"
        error "Run './scripts/create-opkg-feed.sh' first."
        exit 1
    fi
    
    if ! command -v git &>/dev/null; then
        error "git not found."
        exit 1
    fi
    
    # Check we're in a git repo
    if ! git rev-parse --git-dir &>/dev/null; then
        error "Not a git repository."
        exit 1
    fi
    
    info "Prerequisites satisfied."
}

# === Deploy to gh-pages ===
deploy_feed() {
    step "Deploying feed to gh-pages branch..."
    
    local temp_dir
    temp_dir=$(mktemp -d /tmp/vortex-ghpages.XXXXXX)
    
    if $DRY_RUN; then
        info "[DRY RUN] Would deploy ${FEED_DIR}/ to gh-pages branch"
        info "[DRY RUN] Feed URL: https://vincenzosco.github.io/Vortex-A9100-Linux-Image/opkg/"
        info "[DRY RUN] Version: ${VERSION}"
        echo ""
        info "[DRY RUN] Files to deploy:"
        ls -lh "${FEED_DIR}/"
        return 0
    fi
    
    # Get the gh-pages branch (or create an orphan branch)
    if git branch -a | grep -q 'gh-pages'; then
        info "Fetching existing gh-pages branch..."
        git fetch origin gh-pages 2>/dev/null || true
        git worktree add "${temp_dir}" gh-pages 2>/dev/null || {
            # Branch exists locally but not remote, or other issue
            git worktree add "${temp_dir}" origin/gh-pages 2>/dev/null || {
                warn "Could not fetch gh-pages. Creating fresh orphan branch."
                git worktree add --detach "${temp_dir}"
                cd "${temp_dir}"
                git checkout --orphan gh-pages
                git rm -rf . 2>/dev/null || true
            }
        }
    else
        info "Creating gh-pages branch..."
        git worktree add --detach "${temp_dir}"
        cd "${temp_dir}"
        git checkout --orphan gh-pages
        git rm -rf . 2>/dev/null || true
    fi
    
    cd "${temp_dir}"
    
    # Create index.html for GitHub Pages root
    cat > "index.html" << 'HTML'
<!DOCTYPE html>
<html>
<head><title>Vortex86 A9100 opkg Feed</title></head>
<body>
<h1>Vortex86 A9100 opkg Feed</h1>
<p>opkg package repository for the DM&P Vortex86 A9100 embedded Linux image.</p>
<h2>Repository URL</h2>
<pre>src/gz vortex-stable https://vincenzosco.github.io/Vortex-A9100-Linux-Image/opkg/</pre>
<h2>Usage</h2>
<pre>
# On the Vortex86 A9100:
opkg update
opkg list | grep vortex
opkg install vortex-os-update
</pre>
<p>See the <a href="https://github.com/vincenzosco/Vortex-A9100-Linux-Image">main repository</a> for build instructions.</p>
</body>
</html>
HTML
    
    # Create opkg/ subdirectory with feed
    mkdir -p opkg
    cp "${FEED_DIR}/Packages.gz" opkg/
    for ipk in "${FEED_DIR}"/*.ipk; do
        if [ -f "${ipk}" ]; then
            cp "${ipk}" opkg/
        fi
    done
    
    # Create a version file
    echo "${VERSION}" > opkg/version.txt
    date > opkg/deployed.txt
    
    # Commit and push
    git add -A
    if git diff --cached --quiet; then
        info "No changes to deploy."
    else
        git commit -m "Deploy opkg feed v${VERSION}"
        info "Pushing to origin/gh-pages..."
        git push origin gh-pages
        info "Deploy complete!"
    fi
    
    # Cleanup worktree
    cd "${SCRIPT_DIR}"
    git worktree remove "${temp_dir}" 2>/dev/null || true
    rm -rf "${temp_dir}"
}

# === Show result ===
show_result() {
    echo ""
    info "========================================"
    info "Feed Deployed!"
    info "========================================"
    echo ""
    echo "  Feed URL:"
    echo "    https://vincenzosco.github.io/Vortex-A9100-Linux-Image/opkg/"
    echo ""
    echo "  opkg.conf entry:"
    echo "    src/gz vortex-stable https://vincenzosco.github.io/Vortex-A9100-Linux-Image/opkg/"
    echo ""
    echo "  On the Vortex86 A9100:"
    echo "    opkg update"
    echo "    opkg install vortex-os-update"
    echo ""
    echo "  Repository:"
    echo "    https://github.com/vincenzosco/Vortex-A9100-Linux-Image"
    echo ""
}

# === Main ===
main() {
    echo ""
    echo "=============================="
    echo " Vortex86 A9100 opkg Feed Deployer"
    echo " Version: ${VERSION}"
    echo "=============================="
    echo ""
    
    check_prereqs
    deploy_feed
    show_result
}

main "$@"
